vendor: Huawei
name: Huawei Cloud Container Engine
version: 2.10
website_url: http://www.huaweicloud.com/product/cce.html
documentation_url: http://support.huaweicloud.com/cce/index.html
product_logo_url: http://www.huawei.com/Assets/CBG/img/logo.png
